development:
  adapter: mysql
  database: guidelines_development
  username: root
  password: c45p3r
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql
  database: guidelines_test
  username: root
  password: c45p3r
  pool: 5
  timeout: 5000
  encoding: utf8
